fromager:
  n_proc_for_build: 4

  external:
    rdma-core:
      prefix: ~
      version: ~
    hcoll:
      prefix: ~
      version: ~
    gdrcopy:
      prefix: ~
      version: ~
    slurm:
      prefix: ~
      version: ~