#include <algorithm>
#include <database/config.hpp>
#include <filesystem>
#include <parser/parser_internal.hpp>
#include <string>
#include <utils/bash_utils.hpp>
#include <utils/yaml_utils.hpp>
#include <vector>

namespace {

    /**
     * @brief Find a release matching a given version string.
     *
     * Performs a linear search over the source's release list to locate the
     * entry whose @ref Release::version equals @p version.
     *
     * @param source  The source descriptor whose releases are searched.
     * @param version The exact version string to match (e.g. "3.1.4").
     *
     * @return A pointer to the matching @ref Release, or @c nullptr if no
     *         release with that version exists.
     */
    const Release* selected_release(const Source& source, const std::string& version) {
        const auto release = std::find_if(
            source.releases.begin(), source.releases.end(),
            [&version](const Release& candidate) { return candidate.version == version; });
        return release == source.releases.end() ? nullptr : &*release;
    }

    /**
     * @brief Determine the archive extension from a tarball download URL.
     *
     * Scans the URL for well-known archive extensions in priority order:
     * `.tar.zst`, `.tar.bz2`, `.tar.gz`, `.tar.xz`, `.tgz`, `.tar`.
     * The first match is returned.
     *
     * @param url  The download URL string to inspect.
     *
     * @return The matched extension string (including the leading dot).
     *
     * @warning Terminates the program via @c user_config_error() if the URL
     *          contains none of the recognised archive extensions.
     */
    std::string tarball_extension(const std::string& url) {
        static const std::vector<std::string> extensions = {".tar.zst", ".tar.bz2", ".tar.gz",
                                                            ".tar.xz",  ".tgz",     ".tar"};
        for (const std::string& extension : extensions) {
            if (url.find(extension) != std::string::npos) {
                return extension;
            }
        }
        user_config_error("tarball URL has no supported archive extension: " + url);
    }

    /**
     * @brief Generate and append shell commands for downloading and unpacking a
     *        remote source artifact.
     *
     * Handles all remote @ref SourceType variants (Git, Script, Zip, and
     * tarball).  For each type the function:
     *   1. Checks whether a pre-built cache of the unpacked source exists;
     *      if so, extracts from cache and returns immediately.
     *   2. Downloads / clones the source using the appropriate tool
     *      (shallow_clone.sh, wget, or unpack.sh).
     *   3. Archives the newly-obtained source tree into a cache tarball so
     *      that subsequent runs can skip the download step.
     *   4. Changes into the `source` working directory.
     *
     * Template placeholders in the URL, tag, and other scalar fields are
     * resolved via @c resolve_parser_scalar() before use.
     *
     * @param package  The resolved user package whose source is being fetched.
     * @param release  The specific release (version) to download.
     * @param context  The parser context providing settings (cache prefix,
     *                 kez_home path) and template resolution state.
     * @param commands Output vector to which generated bash commands are
     *                 appended.  Existing entries are preserved.
     *
     * @note The Git path uses @c tools/shallow_clone.sh to avoid downloading
     *       full history.  The tarball path uses @c tools/unpack.sh which
     *       detects the archive format automatically.
     * @note The Script type with no URL returns immediately (source is
     *       generated by the recipe body rather than downloaded).
     *
     * @warning Terminates via @c user_config_error() if a cache path exists
     *          but is a regular file (expected) rather than a directory.
     * @warning Terminates via @c user_config_error() if a Script or tarball
     *          release has no URL and the source type is not Script.
     */
    void append_remote_source_commands(const ParsedUserPackage& package, const Release& release,
                                       UserConfigParserContext& context,
                                       std::vector<std::string>& commands) {
        // Attempt to use a cached tarball of the already-unpacked source tree.
        // Returns true and appends extract + cd commands when the cache exists.
        auto use_cache = [&](bool source_is_file) {
            std::string cache_name = package.requested_name + "-" + release.version;
            const std::filesystem::path cache_path =
                context.settings.cache_prefix / (cache_name + ".tar.gz");
            if (!std::filesystem::exists(cache_path)) {
                return false;
            }
            if (std::filesystem::is_directory(cache_path)) {
                user_config_error("cache path exists but is not a file: " + cache_path.string());
            }
            commands.push_back("tar -xzf " + shell_single_quote(cache_path.string()));
            if (!source_is_file) {
                commands.push_back("cd source");
            }
            return true;
        };

        // Archive the current `source` directory into the cache as a tarball.
        auto pack_as_cache = [&]() {
            std::string cache_name = package.requested_name + "-" + release.version;
            const std::filesystem::path cache_path =
                context.settings.cache_prefix / (cache_name + ".tar.gz");
            commands.push_back("mkdir -p " +
                               shell_single_quote(context.settings.cache_prefix.string()));
            commands.push_back("tar -czf " + shell_single_quote(cache_path.string()) +
                               " --format=posix -z source");
        };

        const Source& source = *package.database_config->source;
        if (source.type == SourceType::Git) {
            if (use_cache(false)) return;
            const std::string url = resolve_parser_scalar(*source.url, context);
            const std::string tag = resolve_parser_scalar(*release.tag, context);
            const std::filesystem::path helper =
                context.settings.kez_home / "tools" / "shallow_clone.sh";
            commands.push_back("bash " + shell_single_quote(helper.string()) + " " +
                               shell_single_quote(url) + " " + shell_single_quote(tag) + " source");
            pack_as_cache();
            commands.push_back("cd source");
            return;
        }

        if (!release.url.has_value()) {
            if (source.type == SourceType::Script) {
                return;
            }
            user_config_error("release '" + release.version + "' for package '" +
                              package.requested_name + "' has no URL");
        }

        const std::string url = resolve_parser_scalar(*release.url, context);
        if (source.type == SourceType::Script) {
            if (use_cache(true)) return;
            commands.push_back(
                "wget --quiet --show-progress --no-check-certificate --output-document=source " +
                shell_single_quote(url));
            pack_as_cache();
            return;
        }

        const std::filesystem::path helper = context.settings.kez_home / "tools" / "unpack.sh";
        if (source.type == SourceType::Zip) {
            if (use_cache(false)) return;
            commands.push_back("wget --quiet --show-progress --no-check-certificate "
                               "--output-document=source.zip " +
                               shell_single_quote(url));
            commands.push_back("bash " + shell_single_quote(helper.string()) +
                               " source.zip source");
            commands.push_back("rm source.zip");
            pack_as_cache();
            commands.push_back("cd source");
            return;
        }

        if (use_cache(false)) return;
        const std::string extension = tarball_extension(url);
        const std::string archive   = "source" + extension;
        commands.push_back("wget --quiet --show-progress --no-check-certificate "
                           "--output-document=" +
                           shell_single_quote(archive) + " " + shell_single_quote(url));
        commands.push_back("bash " + shell_single_quote(helper.string()) + " " +
                           shell_single_quote(archive) + " source");
        commands.push_back("rm " + shell_single_quote(archive));
        pack_as_cache();
        commands.push_back("cd source");
    }

}  // namespace

/**
 * @brief Generate the shell source-fetch commands for a resolved user package.
 *
 * This is the top-level entry point for producing the bash commands that
 * obtain a package's source tree.  It supports two modes:
 *
 *   **Remote source** -- When the package's database configuration declares
 *   a @ref Source with releases, the version specified in the user
 *   configuration is looked up via @c selected_release().  If found, the
 *   download / unpack / cache logic in @c append_remote_source_commands()
 *   is invoked.
 *
 *   **Local source** -- If the version string is not a known release, it
 *   must follow the format `<version>@<path>`, where the part after `@` is
 *   a path to an existing local directory.  The directory is copied in-place
 *   (via `cp -a`) and the working directory is changed to it.
 *
 * If the package has no source metadata (e.g. a system or vendor package),
 * the function returns immediately without appending any commands.
 *
 * @param package  The resolved user package whose source should be fetched.
 * @param context  The parser context providing settings, template resolution,
 *                 and error-message context.
 * @param commands Output vector to which the generated bash commands are
 *                 appended.  Existing entries are preserved.
 *
 * @warning Terminates via @c user_config_error() if:
 *          - The user configuration is missing the required "version" field.
 *          - The version string is neither a known release name nor a valid
 *            `<version>@<local-path>` reference.
 *          - The local path referenced after `@` does not exist or is not a
 *            directory.
 *
 * @see append_remote_source_commands()  Handles all remote source types.
 * @see selected_release()               Searches releases by version string.
 */
void append_source_commands(const ParsedUserPackage& package, UserConfigParserContext& context,
                            std::vector<std::string>& commands) {
    if (!package.database_config->source.has_value()) {
        return;
    }
    if (!yaml_has(package.user_config, "version")) {
        user_config_error("package '" + package.requested_name + "' is missing its version");
    }

    const std::string version = yaml_scalar(package.user_config["version"], "package version");
    const Release* release    = selected_release(*package.database_config->source, version);
    if (release != nullptr) {
        append_remote_source_commands(package, *release, context, commands);
        return;
    }

    const std::size_t separator = version.find('@');
    if (separator == std::string::npos || separator + 1 == version.size()) {
        user_config_error("package '" + package.requested_name + "' version '" + version +
                          "' is neither a known release nor '<version>@<local-path>'");
    }
    const std::filesystem::path source_path = version.substr(separator + 1);
    if (!std::filesystem::is_directory(source_path)) {
        user_config_error("local source directory does not exist: " + source_path.string());
    }
    commands.push_back("cp -a " + shell_single_quote(source_path.string()) + " source");
    commands.push_back("cd source");
}
