fromager:
  n_proc_for_build: 4

  default_compiler: system

  paths:
    cellars: cellars
    system: cellars/system
    utilities: cellars/utilities
    compilers: cellars/compilers
    mpis: cellars/mpis
    vendors: cellars/vendors
    factories: factories

  external:
    rdma-core:
      prefix: ~
      version: ~
    hcoll:
      prefix: ~
      version: ~
    gdrcopy:
      prefix: ~
      version: ~
    slurm:
      prefix: ~
      version: ~