---
settings:
    n_proc_for_build: 4
    max_n_jobs_for_build: 2

    default_compiler: system

    external:
        rdma-core:
            prefix:
            version:
        gdrcopy:
            prefix:
            version:
        slurm:
            prefix:
            version:
