---
settings:
    n_proc_for_build: 32
    max_n_jobs_for_build: 8

    default_compiler: system

    external:
        rdma-core:
            prefix: /usr
            version: 51.0
        gdrcopy:
            prefix:
            version:
        slurm:
            prefix: /cm/shared/apps/slurm/23.02.7
            version: 23.02.7
