fromager:
  n_proc_for_build: 32

  paths:
    cellars: cellars
    system: cellars/system
    utilities: cellars/utilities
    compilers: cellars/compilers
    mpis: cellars/mpis
    vendors: cellars/vendors
    factories: factories

  external:
    rdma-core:
      prefix: /usr
      version: 51.0
    hcoll:
      prefix: /opt/mellanox/hcoll
      version: 4.8.3227
    gdrcopy:
      prefix: ~
      version: ~
    slurm:
      prefix: /cm/shared/apps/slurm/23.02.7
      version: 23.02.7
