fromager:
  n_proc_for_build: 32

  default_compiler: system

  paths:
    cellars: cellars
    system: cellars/system
    utilities: cellars/utilities
    compilers: cellars/compilers
    mpis: cellars/mpis
    vendors: cellars/vendors
    factories: factories
    modulefiles: modulefiles

  external:
    rdma-core:
      prefix: /usr
      version: 61.0
    hcoll:
      prefix: ~
      version: ~
    gdrcopy:
      prefix: /usr
      version: 2.5.2
    slurm:
      prefix: /cm/local/apps/slurm/24.11
      version: 24.11
