#pragma once

#define COLOR_RED "\033[31m"
#define COLOR_GREEN "\033[32m"
#define COLOR_YELLOW "\033[33m"
#define COLOR_BLUE "\033[34m"
#define COLOR_MAGENTA "\033[35m"
#define COLOR_CYAN "\033[36m"
#define COLOR_RESET "\033[0m"

#define INFO_COLOR COLOR_BLUE
#define WARNING_COLOR COLOR_YELLOW
#define ERROR_COLOR COLOR_RED
#define SUCCESS_COLOR COLOR_GREEN