#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "$1" ]; then
    echo "Usage: $0 <gcc-prefix>"
    exit 1
fi

GCC_PREFIX="$1"

### --- Post-Installation Specs Configuration ---

# 1. Locate where the specs file should live
# We use the compiler itself to tell us its internal library path
SPEC_DIR=$("${GCC_PREFIX}/bin/gcc" -print-libgcc-file-name | xargs dirname)
SPEC_FILE="${SPEC_DIR}/specs"

if [ -f ${SCRIPT_DIR}/../bin/print_info ]; then
    ${SCRIPT_DIR}/../bin/print_info "Generating specs file at: ${SPEC_FILE}"
else
    echo "Generating specs file at: ${SPEC_FILE}"
fi

# 2. Find which directory has the shared libraries (lib64 or lib)
RPATH_DIR=""
for dir in "lib64" "lib"; do
    if ls "${GCC_PREFIX}/${dir}"/libgcc_s.* >/dev/null 2>&1; then
        RPATH_DIR="${GCC_PREFIX}/${dir}"
        break
    fi
done

# 3. Create/Dump the initial specs
# We mimic Spack's logic of stripping trailing whitespace, then appending our blocks
SPECS_CONTENT=$("${GCC_PREFIX}/bin/gcc" -dumpspecs)
printf "%s" "${SPECS_CONTENT}" > "${SPEC_FILE}"
printf "\n\n# Generated by Kez\n\n" >> "${SPEC_FILE}"

# 4. Inject RPATH into *link_libgcc
if [ -n "$RPATH_DIR" ]; then
    printf "*link_libgcc:\n+ -rpath %s\n\n" "${RPATH_DIR}" >> "${SPEC_FILE}"
fi

# 5. Handle Binutils search path (if binutils is in our prefix)
if [ -f "${GCC_PREFIX}/bin/ld" ]; then
    printf "*self_spec:\n+ -B%s/bin\n\n" "${GCC_PREFIX}" >> "${SPEC_FILE}"
fi

# 6. Optional: Default to 'mold' linker if present
# This mirrors the Spack "+mold" logic
if [ -f "${GCC_PREFIX}/bin/mold" ]; then
    printf "*self_spec:\n+ -B%s/bin %%{!fuse-ld*:-fuse-ld=mold}\n\n" "${GCC_PREFIX}" >> "${SPEC_FILE}"
fi

# 7. Fix libgomp (OpenMP) specs if they exist
# This ensures OpenMP binaries also find their runtime libraries
for dir in "lib64" "lib"; do
    GOMP_SPEC="${GCC_PREFIX}/${dir}/libgomp.spec"
    if [ -f "$GOMP_SPEC" ]; then
        echo "Patching libgomp.spec in ${dir}..."
        cp "$GOMP_SPEC" "${GOMP_SPEC}.orig"
        awk -v rpath_dir="${GCC_PREFIX}/${dir}" '
        /^\*link_gomp:/ {
            printf "\n\n# Generated by Kez\n\n"
            printf "%s -rpath %s\n\n", $0, rpath_dir
            next
        }
        { print }
        ' "${GOMP_SPEC}.orig" > "$GOMP_SPEC"
    fi
done

chmod 644 "${SPEC_FILE}"
if [ -f ${SCRIPT_DIR}/../bin/print_info ]; then
    ${SCRIPT_DIR}/../bin/print_info "Specs configuration complete."
else
    echo "Specs configuration complete."
fi
